version: '3'
services:
  app:
    container_name: swiftsheet-app
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo
    depends_on:
      - mongo
    environment:
        - DOCKER=true
        - MONGOURL=mongodb://mongo:27017/swiftsheet

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
